/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VieEnFranceRouteImport } from './routes/vie-en-france'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LeConsulatRouteImport } from './routes/le-consulat'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AccessibiliteRouteImport } from './routes/accessibilite'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ActualitesIndexRouteImport } from './routes/actualites/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ActualitesSlugRouteImport } from './routes/actualites/$slug'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamIndexRouteImport } from './routes/admin/team/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminOrgsIndexRouteImport } from './routes/admin/orgs/index'
import { Route as AdminAuditLogsIndexRouteImport } from './routes/admin/audit-logs/index'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin/announcements/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminTeamNewRouteImport } from './routes/admin/team/new'
import { Route as AdminServicesNewRouteImport } from './routes/admin/services/new'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as AdminOrgsNewRouteImport } from './routes/admin/orgs/new'
import { Route as AdminOrgsOrgIdRouteImport } from './routes/admin/orgs/$orgId'
import { Route as AdminTeamMemberIdEditRouteImport } from './routes/admin/team/$memberId.edit'
import { Route as AdminServicesServiceIdEditRouteImport } from './routes/admin/services/$serviceId_.edit'
import { Route as AdminPostsPostIdEditRouteImport } from './routes/admin/posts/$postId.edit'
import { Route as AdminOrgsOrgIdEditRouteImport } from './routes/admin/orgs/$orgId_.edit'

const VieEnFranceRoute = VieEnFranceRouteImport.update({
  id: '/vie-en-france',
  path: '/vie-en-france',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LeConsulatRoute = LeConsulatRouteImport.update({
  id: '/le-consulat',
  path: '/le-consulat',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibiliteRoute = AccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamIndexRoute = AdminTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrgsIndexRoute = AdminOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsIndexRoute = AdminAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamNewRoute = AdminTeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrgsNewRoute = AdminOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrgsOrgIdRoute = AdminOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamMemberIdEditRoute = AdminTeamMemberIdEditRouteImport.update({
  id: '/team/$memberId/edit',
  path: '/team/$memberId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesServiceIdEditRoute =
  AdminServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId_/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPostsPostIdEditRoute = AdminPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrgsOrgIdEditRoute = AdminOrgsOrgIdEditRouteImport.update({
  id: '/orgs/$orgId_/edit',
  path: '/orgs/$orgId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accessibilite': typeof AccessibiliteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/integration': typeof IntegrationRoute
  '/le-consulat': typeof LeConsulatRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/vie-en-france': typeof VieEnFranceRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/orgs/$orgId': typeof AdminOrgsOrgIdRoute
  '/admin/orgs/new': typeof AdminOrgsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/orgs': typeof AdminOrgsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/orgs/$orgId/edit': typeof AdminOrgsOrgIdEditRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/admin/team/$memberId/edit': typeof AdminTeamMemberIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/integration': typeof IntegrationRoute
  '/le-consulat': typeof LeConsulatRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/vie-en-france': typeof VieEnFranceRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/orgs/$orgId': typeof AdminOrgsOrgIdRoute
  '/admin/orgs/new': typeof AdminOrgsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/audit-logs': typeof AdminAuditLogsIndexRoute
  '/admin/orgs': typeof AdminOrgsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/team': typeof AdminTeamIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/orgs/$orgId/edit': typeof AdminOrgsOrgIdEditRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/admin/team/$memberId/edit': typeof AdminTeamMemberIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accessibilite': typeof AccessibiliteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/integration': typeof IntegrationRoute
  '/le-consulat': typeof LeConsulatRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/vie-en-france': typeof VieEnFranceRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/orgs/$orgId': typeof AdminOrgsOrgIdRoute
  '/admin/orgs/new': typeof AdminOrgsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/admin/team/new': typeof AdminTeamNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/audit-logs/': typeof AdminAuditLogsIndexRoute
  '/admin/orgs/': typeof AdminOrgsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/team/': typeof AdminTeamIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/orgs/$orgId_/edit': typeof AdminOrgsOrgIdEditRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/services/$serviceId_/edit': typeof AdminServicesServiceIdEditRoute
  '/admin/team/$memberId/edit': typeof AdminTeamMemberIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/accessibilite'
    | '/confidentialite'
    | '/contact'
    | '/faq'
    | '/integration'
    | '/le-consulat'
    | '/mentions-legales'
    | '/vie-en-france'
    | '/actualites/$slug'
    | '/services/$slug'
    | '/actualites'
    | '/admin/'
    | '/services'
    | '/admin/orgs/$orgId'
    | '/admin/orgs/new'
    | '/admin/posts/new'
    | '/admin/services/new'
    | '/admin/team/new'
    | '/admin/users/$userId'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/orgs'
    | '/admin/posts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/orgs/$orgId/edit'
    | '/admin/posts/$postId/edit'
    | '/admin/services/$serviceId/edit'
    | '/admin/team/$memberId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibilite'
    | '/confidentialite'
    | '/contact'
    | '/faq'
    | '/integration'
    | '/le-consulat'
    | '/mentions-legales'
    | '/vie-en-france'
    | '/actualites/$slug'
    | '/services/$slug'
    | '/actualites'
    | '/admin'
    | '/services'
    | '/admin/orgs/$orgId'
    | '/admin/orgs/new'
    | '/admin/posts/new'
    | '/admin/services/new'
    | '/admin/team/new'
    | '/admin/users/$userId'
    | '/admin/announcements'
    | '/admin/audit-logs'
    | '/admin/orgs'
    | '/admin/posts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/orgs/$orgId/edit'
    | '/admin/posts/$postId/edit'
    | '/admin/services/$serviceId/edit'
    | '/admin/team/$memberId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/accessibilite'
    | '/confidentialite'
    | '/contact'
    | '/faq'
    | '/integration'
    | '/le-consulat'
    | '/mentions-legales'
    | '/vie-en-france'
    | '/actualites/$slug'
    | '/services/$slug'
    | '/actualites/'
    | '/admin/'
    | '/services/'
    | '/admin/orgs/$orgId'
    | '/admin/orgs/new'
    | '/admin/posts/new'
    | '/admin/services/new'
    | '/admin/team/new'
    | '/admin/users/$userId'
    | '/admin/announcements/'
    | '/admin/audit-logs/'
    | '/admin/orgs/'
    | '/admin/posts/'
    | '/admin/services/'
    | '/admin/settings/'
    | '/admin/team/'
    | '/admin/users/'
    | '/admin/orgs/$orgId_/edit'
    | '/admin/posts/$postId/edit'
    | '/admin/services/$serviceId_/edit'
    | '/admin/team/$memberId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccessibiliteRoute: typeof AccessibiliteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  IntegrationRoute: typeof IntegrationRoute
  LeConsulatRoute: typeof LeConsulatRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  VieEnFranceRoute: typeof VieEnFranceRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vie-en-france': {
      id: '/vie-en-france'
      path: '/vie-en-france'
      fullPath: '/vie-en-france'
      preLoaderRoute: typeof VieEnFranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-consulat': {
      id: '/le-consulat'
      path: '/le-consulat'
      fullPath: '/le-consulat'
      preLoaderRoute: typeof LeConsulatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/': {
      id: '/admin/team/'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orgs/': {
      id: '/admin/orgs/'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs/': {
      id: '/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/new': {
      id: '/admin/team/new'
      path: '/team/new'
      fullPath: '/admin/team/new'
      preLoaderRoute: typeof AdminTeamNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/new': {
      id: '/admin/services/new'
      path: '/services/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orgs/new': {
      id: '/admin/orgs/new'
      path: '/orgs/new'
      fullPath: '/admin/orgs/new'
      preLoaderRoute: typeof AdminOrgsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orgs/$orgId': {
      id: '/admin/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/admin/orgs/$orgId'
      preLoaderRoute: typeof AdminOrgsOrgIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/$memberId/edit': {
      id: '/admin/team/$memberId/edit'
      path: '/team/$memberId/edit'
      fullPath: '/admin/team/$memberId/edit'
      preLoaderRoute: typeof AdminTeamMemberIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/$serviceId_/edit': {
      id: '/admin/services/$serviceId_/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/admin/services/$serviceId/edit'
      preLoaderRoute: typeof AdminServicesServiceIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$postId/edit': {
      id: '/admin/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/admin/posts/$postId/edit'
      preLoaderRoute: typeof AdminPostsPostIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orgs/$orgId_/edit': {
      id: '/admin/orgs/$orgId_/edit'
      path: '/orgs/$orgId/edit'
      fullPath: '/admin/orgs/$orgId/edit'
      preLoaderRoute: typeof AdminOrgsOrgIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrgsOrgIdRoute: typeof AdminOrgsOrgIdRoute
  AdminOrgsNewRoute: typeof AdminOrgsNewRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminTeamNewRoute: typeof AdminTeamNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
  AdminAuditLogsIndexRoute: typeof AdminAuditLogsIndexRoute
  AdminOrgsIndexRoute: typeof AdminOrgsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTeamIndexRoute: typeof AdminTeamIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminOrgsOrgIdEditRoute: typeof AdminOrgsOrgIdEditRoute
  AdminPostsPostIdEditRoute: typeof AdminPostsPostIdEditRoute
  AdminServicesServiceIdEditRoute: typeof AdminServicesServiceIdEditRoute
  AdminTeamMemberIdEditRoute: typeof AdminTeamMemberIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrgsOrgIdRoute: AdminOrgsOrgIdRoute,
  AdminOrgsNewRoute: AdminOrgsNewRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminTeamNewRoute: AdminTeamNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
  AdminAuditLogsIndexRoute: AdminAuditLogsIndexRoute,
  AdminOrgsIndexRoute: AdminOrgsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTeamIndexRoute: AdminTeamIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminOrgsOrgIdEditRoute: AdminOrgsOrgIdEditRoute,
  AdminPostsPostIdEditRoute: AdminPostsPostIdEditRoute,
  AdminServicesServiceIdEditRoute: AdminServicesServiceIdEditRoute,
  AdminTeamMemberIdEditRoute: AdminTeamMemberIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccessibiliteRoute: AccessibiliteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  IntegrationRoute: IntegrationRoute,
  LeConsulatRoute: LeConsulatRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  VieEnFranceRoute: VieEnFranceRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
